"""Shared geometry-to-SDF helpers for the TadeoeCar world generators.

Both worlds are emitted from a single Python list of primitives, and the Nav2
occupancy grid is derived from that same list. That is the whole point of
generating them: a world and a map that are written by hand drift apart the
moment either is edited, and the symptom - Nav2 planning around walls that are
not there - looks like a localisation bug rather than a stale file.

Nothing here is downloaded from Fuel: boxes, cylinders and planes only, so the
worlds open on a machine with no network and no model cache.
"""

import collections
import math
import os

# Wheel radius is 0.1 m and the LiDAR plane sits 0.53 m above the ground, so
# anything shorter than the LiDAR plane is invisible to a 2D scan even though
# the robot would hit it. Every generator asserts on that gap rather than
# leaving it to be discovered by driving into something.
LIDAR_Z = 0.53
WHEEL_RADIUS = 0.1

RES = 0.05
MARGIN = 1.0
FREE, OCC, UNKNOWN = 254, 0, 205

# Friction. mu acts along the wheel's rolling direction and mu2 across it. On a
# 4WS robot the second one matters in its own right: a crab manoeuvre asks all
# four tyres to roll sideways relative to the chassis, and the steering angle
# is what makes that legal, so lateral grip is a real parameter and not a
# rounding detail.
MU_CEMENT = 1.00
MU_ASPHALT = 0.90
MU_GRAVEL = 0.55
MU_SAND = 0.30

# Each material carries a texture as well as a colour. Flat-shaded colour is
# what a synthetic world defaults to and it is exactly what visual SLAM cannot
# work with: a corner detector needs intensity gradients, and a uniformly
# coloured wall has none anywhere except at its silhouette. Measured on the
# untextured factory, RTAB-Map's visual odometry ran at 0 to 9 inliers against
# a threshold of 10 and lost tracking within seconds of moving.
#
# The textures are generated by scripts/generate_textures.py rather than
# downloaded, so they can be regenerated and nothing binary arrives without a
# recipe. A box gets one tile per face, so long surfaces are split into panels
# by the world generators - that puts a tile boundary every couple of metres
# and gives the detector real corners at a scale the camera resolves.
CEMENT = (0.62, 0.62, 0.60)
ASPHALT = (0.24, 0.24, 0.26)
GRAVEL = (0.45, 0.42, 0.38)
SAND = (0.78, 0.68, 0.45)
WALL_MAT = (0.85, 0.85, 0.82)
STEEL = (0.35, 0.45, 0.55)
RACK = (0.30, 0.42, 0.60)
CRATE = (0.55, 0.40, 0.24)
DRUM = (0.70, 0.45, 0.15)
PAINT = (0.90, 0.75, 0.15)

TEXTURE = {
    CEMENT: 'concrete',
    ASPHALT: 'asphalt',
    GRAVEL: 'gravel',
    SAND: 'sand',
    WALL_MAT: 'painted_wall',
    STEEL: 'steel',
    RACK: 'steel',
    CRATE: 'crate',
    DRUM: 'steel',
    PAINT: None,
}


class Layout:
    """A list of primitives plus the checks that keep it drivable."""

    def __init__(self, name):
        self.name = name
        # (name, cx, cy, cz, sx, sy, sz, mat, mu, pitch, kind)
        self.boxes = []
        # (name, cx, cy, base_z, radius, height, mat, mu, kind)
        self.cylinders = []

    def box(self, name, cx, cy, cz, sx, sy, sz, mat=WALL_MAT, mu=MU_CEMENT,
            pitch=0.0, kind='obstacle'):
        self.boxes.append((name, cx, cy, cz, sx, sy, sz, mat, mu, pitch, kind))

    def wall(self, name, cx, cy, sx, sy, sz=2.5, mat=WALL_MAT, panel=2.5):
        """A wall, emitted as panels of at most ``panel`` metres.

        One box would be one texture tile stretched over the whole run, which
        is a smooth gradient and no help to a feature detector. Splitting it
        puts a seam every couple of metres, and the seams are what the camera
        tracks. The occupancy grid is unchanged either way: the panels are
        flush and butt against each other.
        """
        long_axis = 0 if sx >= sy else 1
        length = sx if long_axis == 0 else sy
        n = max(1, int(round(length / panel)))
        step = length / n
        for i in range(n):
            offset = -length / 2 + step * (i + 0.5)
            px = cx + offset if long_axis == 0 else cx
            py = cy if long_axis == 0 else cy + offset
            psx = step if long_axis == 0 else sx
            psy = sy if long_axis == 0 else step
            suffix = '' if n == 1 else f'_{i}'
            self.box(f'{name}{suffix}', px, py, sz / 2, psx, psy, sz, mat)

    def slab(self, name, cx, cy, sx, sy, top_z, mat=CEMENT, mu=MU_CEMENT,
             thickness=0.02):
        """A drivable surface: never an obstacle, never in the occupancy grid."""
        self.box(name, cx, cy, top_z - thickness / 2, sx, sy, thickness,
                 mat, mu, 0.0, 'floor')

    def ceiling(self, name, cx, cy, sx, sy, bottom_z, mat=WALL_MAT,
                thickness=0.2, panel=4.0):
        """Overhead structure: above the robot, so not on the floor plan.

        A roof is not decoration here. Without one the camera - which sits
        0.30 m off the ground and looks along a 110 degree field of view -
        spends the top third of every frame on empty background: no geometry,
        no depth, no features. Measured on the roofless factory, 27 % of depth
        pixels came back non-finite and RTAB-Map's visual odometry failed
        registration on 13 % of frames. A roof puts textured geometry at a
        known distance across the part of the image that had none.

        It never enters the occupancy grid and never triggers the blind-band
        height check, because the robot drives underneath it.
        """
        n = max(1, int(round(max(sx, sy) / panel)))
        long_axis = 0 if sx >= sy else 1
        length = sx if long_axis == 0 else sy
        step = length / n
        for i in range(n):
            offset = -length / 2 + step * (i + 0.5)
            px = cx + offset if long_axis == 0 else cx
            py = cy if long_axis == 0 else cy + offset
            psx = step if long_axis == 0 else sx
            psy = sy if long_axis == 0 else step
            self.box(f'{name}_{i}', px, py, bottom_z + thickness / 2,
                     psx, psy, thickness, mat, MU_CEMENT, 0.0, 'ceiling')

    def ramp(self, name, x0, x1, cy, width, rise, thickness=0.02,
             mat=CEMENT, mu=MU_CEMENT):
        """A thin tilted plate resting ON the floor at its low end.

        The obvious alternative - a thick slab whose top face meets z=0 flush,
        with the rest of it buried under the ground plane - is wrong. It leaves
        a strip at the foot where a wheel touches the ground plane and the
        slab's top face just below it at the same time, and the solver resolves
        that ambiguity by ejecting the robot. It looks exactly like the robot
        sinking through the floor.

        The plate resting on top costs a lip at the foot instead, one plate
        thickness high, which 0.1 m wheels clear without noticing.

        Thickness measured vertically is ``thickness / cos(theta)`` and theta
        depends on it, so the pair is solved by iterating; it converges in two
        passes at this scale.
        """
        run = x1 - x0
        theta = math.atan2(rise - thickness, run)
        for _ in range(4):
            lip = thickness / math.cos(theta)
            theta = math.atan2(rise - lip, run)
        length = math.hypot(run, rise - lip)

        # Two conditions fix the plate: the top face ends flush with the
        # platform at (x1, rise), and the low bottom corner rests on z = 0.
        # Solve for the top-face midpoint, then step half a thickness down the
        # plate's own normal to reach the centre the SDF pose wants.
        cx = (x0 + x1) / 2 + (thickness / 2) * math.sin(theta)
        cz = (lip + rise) / 2 - (thickness / 2) * math.cos(theta)
        self.box(name, cx, cy, cz, length, width, thickness,
                 mat, mu, -theta, kind='floor')
        return theta, lip

    def cyl(self, name, cx, cy, base_z, radius, height, mat=STEEL,
            mu=MU_CEMENT, kind='obstacle'):
        self.cylinders.append((name, cx, cy, base_z, radius, height, mat, mu, kind))

    # ------------------------------------------------------------ checks ----
    def footprints(self):
        """(name, x0, x1, y0, y1, z0, z1) for everything the robot can hit."""
        out = []
        for (n, cx, cy, cz, sx, sy, sz, _, _, _, kind) in self.boxes:
            if kind != 'obstacle':
                continue
            out.append((n, cx - sx / 2, cx + sx / 2, cy - sy / 2, cy + sy / 2,
                        cz - sz / 2, cz + sz / 2))
        for (n, cx, cy, bz, r, h, _, _, kind) in self.cylinders:
            if kind != 'obstacle':
                continue
            out.append((n, cx - r, cx + r, cy - r, cy + r, bz, bz + h))
        return out

    @staticmethod
    def _overlap(a, b, eps=1e-6):
        """True when two boxes share volume.

        The z test is not decoration: a control panel resting on top of a
        machine shares its whole footprint and is not a modelling error, while
        two crates at the same height sharing one are.
        """
        return (a[1] < b[2] - eps and b[1] < a[2] - eps and
                a[3] < b[4] - eps and b[3] < a[4] - eps and
                a[5] < b[6] - eps and b[5] < a[6] - eps)

    def check(self, corridors=(), exempt_prefixes=('wall_', 'barrier_')):
        """Refuse to emit a world the robot cannot use.

        ``corridors`` are (label, x0, x1, y0, y1) rectangles that must stay
        clear - the approach to a ramp, the lane down an aisle. Overlapping
        furniture is rejected too: two boxes sharing space render fine and then
        behave like neither of them in the solver.
        """
        problems = []
        fps = self.footprints()

        for (label, x0, x1, y0, y1) in corridors:
            # A corridor is clear only up to the height the robot occupies;
            # a gantry overhead is not an obstruction.
            lane = (label, x0, x1, y0, y1, 0.0, 0.8)
            for fp in fps:
                if self._overlap(fp, lane):
                    problems.append(f'{fp[0]} blocks the {label} corridor')

        shell = [fp for fp in fps if fp[0].startswith(exempt_prefixes)]
        furniture = [fp for fp in fps if fp not in shell]
        for i, a in enumerate(furniture):
            for b in furniture[i + 1:]:
                if self._overlap(a, b):
                    problems.append(f'{a[0]} overlaps {b[0]}')
            for b in shell:
                if self._overlap(a, b):
                    problems.append(f'{a[0]} overlaps {b[0]}')

        # An obstacle shorter than the LiDAR plane but taller than the wheels
        # can neither be seen nor climbed. Either is fine on its own; the
        # combination is a trap.
        for (n, cx, cy, cz, sx, sy, sz, _, _, _, kind) in self.boxes:
            if kind != 'obstacle':
                continue
            if WHEEL_RADIUS < sz < LIDAR_Z:
                problems.append(
                    f'{n} stands {sz:.2f} m above its own base: too tall to '
                    f'drive over (wheel radius {WHEEL_RADIUS} m) and too short '
                    f'for the LiDAR plane at {LIDAR_Z} m')

        if problems:
            raise AssertionError(
                f'{self.name}: layout is unusable:\n  - ' + '\n  - '.join(problems))

    # --------------------------------------------------------------- SDF ----
    @staticmethod
    def _lights(lights):
        out = ''
        for i, (x, y, z) in enumerate(lights):
            out += f"""
    <light type='point' name='bay_light_{i}'>
      <pose>{x} {y} {z} 0 0 0</pose>
      <cast_shadows>false</cast_shadows>
      <diffuse>0.75 0.74 0.70 1</diffuse>
      <specular>0.12 0.12 0.12 1</specular>
      <attenuation>
        <range>26</range>
        <constant>0.42</constant>
        <linear>0.02</linear>
        <quadratic>0.002</quadratic>
      </attenuation>
    </light>"""
        return out

    @staticmethod
    def _surface(mu):
        return f"""
          <surface>
            <friction>
              <ode>
                <mu>{mu}</mu>
                <mu2>{mu}</mu2>
              </ode>
            </friction>
          </surface>"""

    @staticmethod
    def _material(mat):
        r, g, b = mat
        tex = TEXTURE.get(mat)
        pbr = ''
        if tex:
            # Relative to the WORLD file's own directory. Gazebo resolves a
            # texture URI against the directory of the file that names it, not
            # against GZ_SIM_RESOURCE_PATH, so these live in worlds/materials.
            pbr = f"""
            <pbr>
              <metal>
                <albedo_map>materials/textures/{tex}.png</albedo_map>
                <metalness>0.0</metalness>
                <roughness>0.85</roughness>
              </metal>
            </pbr>"""
        return f"""
          <material>
            <ambient>{r*0.5:.3f} {g*0.5:.3f} {b*0.5:.3f} 1</ambient>
            <diffuse>{r:.3f} {g:.3f} {b:.3f} 1</diffuse>
            <specular>0.1 0.1 0.1 1</specular>{pbr}
          </material>"""

    def _box_model(self, name, cx, cy, cz, sx, sy, sz, mat, mu, pitch, kind):
        return f"""
    <model name='{name}'>
      <static>true</static>
      <pose>{cx:.5f} {cy:.5f} {cz:.5f} 0 {pitch:.6f} 0</pose>
      <link name='link'>
        <collision name='collision'>
          <geometry><box><size>{sx:.5f} {sy:.5f} {sz:.5f}</size></box></geometry>{self._surface(mu)}
        </collision>
        <visual name='visual'>
          <geometry><box><size>{sx:.5f} {sy:.5f} {sz:.5f}</size></box></geometry>{self._material(mat)}
        </visual>
      </link>
    </model>"""

    def _cyl_model(self, name, cx, cy, base_z, radius, height, mat, mu, kind):
        return f"""
    <model name='{name}'>
      <static>true</static>
      <pose>{cx:.5f} {cy:.5f} {base_z + height/2:.5f} 0 0 0</pose>
      <link name='link'>
        <collision name='collision'>
          <geometry><cylinder><radius>{radius}</radius><length>{height}</length></cylinder></geometry>{self._surface(mu)}
        </collision>
        <visual name='visual'>
          <geometry><cylinder><radius>{radius}</radius><length>{height}</length></cylinder></geometry>{self._material(mat)}
        </visual>
      </link>
    </model>"""

    def sdf(self, ground_mu=MU_CEMENT, ground_mat=CEMENT, ambient=0.55,
            background=(0.75, 0.80, 0.85), lights=()):
        """``lights`` are (x, y, z) point lights, for a world with a roof.

        A roofed building lit only by the sun is a building with the lights
        off: the camera sees a dark, low-contrast scene and the feature
        detector has little to work with. Real warehouses have luminaires, and
        so does this one.
        """
        body = ''.join(self._box_model(*b) for b in self.boxes)
        body += ''.join(self._cyl_model(*c) for c in self.cylinders)
        br, bg, bb = background
        gr, gg, gb = ground_mat
        return f"""<sdf version='1.9'>
  <world name='default'>

    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-contact-system" name="gz::sim::systems::Contact"/>
    <!-- IMU. The Sensors system above already covers the LiDAR and the camera,
         but an <sensor type="imu"> publishes nothing at all unless this system
         is loaded in the world: the topic simply never appears and Gazebo logs
         no warning about it. The ZED 2i's IMU is what makes the robot's roll
         and pitch observable instead of assumed, so without this line the EKF
         in tadeocar_perception silently has one input fewer. -->
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>

    <gravity>0 0 -9.8</gravity>
    <physics name='default_physics' type='ode'>
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
      <real_time_update_rate>1000</real_time_update_rate>
    </physics>

    <scene>
      <ambient>{ambient} {ambient} {ambient} 1</ambient>
      <background>{br} {bg} {bb} 1</background>
      <shadows>true</shadows>
    </scene>

{self._lights(lights)}
    <light type='directional' name='sun'>
      <cast_shadows>true</cast_shadows>
      <pose>0 0 12 0 0 0</pose>
      <diffuse>0.9 0.9 0.9 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <attenuation>
        <range>1000</range>
        <constant>0.9</constant>
        <linear>0.01</linear>
        <quadratic>0.001</quadratic>
      </attenuation>
      <direction>-0.4 0.3 -0.9</direction>
    </light>

    <model name='ground_plane'>
      <static>true</static>
      <link name='link'>
        <collision name='collision'>
          <geometry><plane><normal>0 0 1</normal><size>200 200</size></plane></geometry>{self._surface(ground_mu)}
        </collision>
        <visual name='visual'>
          <geometry><plane><normal>0 0 1</normal><size>200 200</size></plane></geometry>
          <material>
            <ambient>{gr*0.5:.3f} {gg*0.5:.3f} {gb*0.5:.3f} 1</ambient>
            <diffuse>{gr:.3f} {gg:.3f} {gb:.3f} 1</diffuse>
            <specular>0.05 0.05 0.05 1</specular>
            <pbr>
              <metal>
                <albedo_map>materials/textures/{TEXTURE.get(ground_mat) or "concrete"}.png</albedo_map>
                <metalness>0.0</metalness>
                <roughness>0.9</roughness>
              </metal>
            </pbr>
          </material>
        </visual>
      </link>
    </model>
{body}

  </world>
</sdf>
"""

    # ---------------------------------------------------------- 2D map ------
    def grid(self, spawn):
        """Occupancy grid seen by a LiDAR plane at ``LIDAR_Z``.

        Obstacles enter it if they rise above that plane relative to their own
        base, which is why each one carries its base height rather than being
        assumed to start on the floor. Surfaces flagged 'floor' are drivable
        and never appear.
        """
        solids = [(cx, cy, sx, sy) for (_, cx, cy, cz, sx, sy, sz, _, _, _, kind)
                  in self.boxes if kind == 'obstacle' and sz > LIDAR_Z]
        disks = [(cx, cy, r) for (_, cx, cy, bz, r, h, _, _, kind)
                 in self.cylinders if kind == 'obstacle' and h > LIDAR_Z]

        xs = [cx - sx / 2 for cx, cy, sx, sy in solids] + [cx - r for cx, cy, r in disks]
        xs += [cx + sx / 2 for cx, cy, sx, sy in solids] + [cx + r for cx, cy, r in disks]
        ys = [cy - sy / 2 for cx, cy, sx, sy in solids] + [cy - r for cx, cy, r in disks]
        ys += [cy + sy / 2 for cx, cy, sx, sy in solids] + [cy + r for cx, cy, r in disks]

        ox, oy = min(xs) - MARGIN, min(ys) - MARGIN
        w = int(round((max(xs) + MARGIN - ox) / RES))
        h = int(round((max(ys) + MARGIN - oy) / RES))
        grid = [[UNKNOWN] * w for _ in range(h)]

        def cell(x, y):
            return int((x - ox) / RES), int((y - oy) / RES)

        for cx, cy, sx, sy in solids:
            c0, r0 = cell(cx - sx / 2, cy - sy / 2)
            c1, r1 = cell(cx + sx / 2, cy + sy / 2)
            for r in range(max(0, r0), min(h, r1 + 1)):
                for c in range(max(0, c0), min(w, c1 + 1)):
                    grid[r][c] = OCC
        for cx, cy, rad in disks:
            c0, r0 = cell(cx - rad, cy - rad)
            c1, r1 = cell(cx + rad, cy + rad)
            for r in range(max(0, r0), min(h, r1 + 1)):
                for c in range(max(0, c0), min(w, c1 + 1)):
                    x, y = ox + (c + 0.5) * RES, oy + (r + 0.5) * RES
                    if (x - cx) ** 2 + (y - cy) ** 2 <= rad ** 2:
                        grid[r][c] = OCC

        # Flood fill free space from the spawn point. Anything the fill cannot
        # reach stays unknown, which is exactly what a robot that starts there
        # would ever be able to map.
        sc, sr = cell(*spawn)
        if grid[sr][sc] == OCC:
            raise AssertionError(f'{self.name}: spawn {spawn} falls inside an obstacle')
        q = collections.deque([(sr, sc)])
        grid[sr][sc] = FREE
        while q:
            r, c = q.popleft()
            for dr, dc in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                rr, cc = r + dr, c + dc
                if 0 <= rr < h and 0 <= cc < w and grid[rr][cc] == UNKNOWN:
                    grid[rr][cc] = FREE
                    q.append((rr, cc))
        return grid, w, h, ox, oy

    def write_map(self, pgm_path, yaml_path, spawn):
        grid, w, h, ox, oy = self.grid(spawn)
        with open(pgm_path, 'wb') as f:
            f.write(f'P5\n{w} {h}\n255\n'.encode())
            for r in range(h - 1, -1, -1):        # PGM row 0 is max y
                f.write(bytes(grid[r]))
        with open(yaml_path, 'w') as f:
            f.write(f"""image: {os.path.basename(pgm_path)}
mode: trinary
resolution: {RES}
origin: [{ox:.3f}, {oy:.3f}, 0.0]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.25
""")
        occ = sum(row.count(OCC) for row in grid)
        free = sum(row.count(FREE) for row in grid)
        print(f'map {w}x{h} ({w*RES:.2f} x {h*RES:.2f} m) origin=({ox:.2f},{oy:.2f}) '
              f'occupied={occ} free={free} -> {pgm_path}')


def workspace_src(here):
    """src/ directory of the workspace, given a scripts/ directory inside it."""
    return os.path.dirname(os.path.dirname(os.path.abspath(here)))
